from typing import Any

class _TableQuery:
    def insert(self, data: Any) -> "_TableQuery": ...
    def execute(self) -> Any: ...

class Client:
    def table(self, name: str) -> _TableQuery: ...

def create_client(url: str, key: str) -> Client: ...
